[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:web_server]
command=uvicorn main:app --host 0.0.0.0 --port 8000
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/web_server.err.log
stdout_logfile=/var/log/supervisor/web_server.out.log

[program:celery_receive]
command=celery --app=tasks worker --loglevel=info -Q celery_receive_message --concurrency=2
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/celery_receive.err.log
stdout_logfile=/var/log/supervisor/celery_receive.out.log

[program:celery_send]
command=celery --app=tasks worker --loglevel=info -Q celery_send_message --concurrency=2
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/celery_send.err.log
stdout_logfile=/var/log/supervisor/celery_send.out.log

[program:celery_agent]
command=celery --app=tasks worker --loglevel=info -Q celery_agent_message --concurrency=2
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/celery_agent.err.log
stdout_logfile=/var/log/supervisor/celery_agent.out.log

[program:celery_beat]
command=celery -A tasks beat --loglevel=info --scheduler celery.beat.PersistentScheduler
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/celery_beat.err.log
stdout_logfile=/var/log/supervisor/celery_beat.out.log

[program:flower]
command=celery --app=tasks flower --port=5555 --basic_auth=%(ENV_FLOWER_USER)s:%(ENV_FLOWER_PASSWORD)s
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/flower.err.log
stdout_logfile=/var/log/supervisor/flower.out.log
